### ISSUE TITLE
Getting started / Gamestate doesn't expose position and hp

### ISSUE THREAD

**Issue by shazz** [sbischoff-ai/pygase#6]
Hi,
I just tried the getting started tutorial but I have a bug, it seems the serialized GameState object returned by `client.access_game_state()` doesn't expose the additional attributes (position and hp) added into the initial game state.

While calling 
```
with client.access_game_state() as game_state:
    print(game_state.position)
    print(game_state.hp)
```

I got:
```
Traceback (most recent call last):
  File "client.py", line 10, in <module>
    print(game_state.position)
AttributeError: 'GameState' object has no attribute 'position'
```

I typed `dir(game_state)`, no position or hp attributes... 

Thanks!
 
Python version: 3.7
Pygase version: 0.3.1

**Comment by shazz** [comment]
By the way, I noticed that using:
```
position = client.try_to(lambda game_state: game_state.position)
```
it works but I don't understand why the `access_game_state()` doesn't work as the position is updated before the client connects so it should already exist no ?

**Comment by sbischoff-ai** [comment]
Sorry for answering almost a year late, I was busy and didn't check my GitHub. I'm sure this is hardly even relevant to you anymore, but maybe this could help someone else.

The behavior you describe is what is expected with your client code:
```client.connect_in_thread(port=8080)

client.register_event_handler("ATTACK_FEEDBACK", print)

with client.access_game_state() as game_state:
    print(dir(game_state))
    # print(game_state.position)
    # print(game_state.hp)
```
The line `print(dir(game_state))` is executed before the first game state update ever reaches the client. Even though you probably run the server on the same computer and the connection is via localhost and not an actual network, the client process will still be much much faster executing a few lines of python code than the game loop will be exchanging packages between server and client. That is exactly what the `try_to` method is for, since your client will need to get started somehow. In the chase example game you can see I have handled that by waiting for the player object to be created server_side (The `while client.player_id is None` loop before the clients actual game loop).
